// Database Siswa DPIB dan TKP SMKN 2 Terbanggi Besar
// Menggunakan variabel global agar bisa diakses oleh semua file HTML yang memanggilnya
window.databaseSiswa = {
    "X-DPIB-1": ["ADAM ILHAM DARMAWAN", "AGUNG SATRIA UTAMA", "AGUSTINA", "AINUL MARDIAH", "ALDIANO AFANDY", "ALI FAHMI SETIOSO", "AMELIA BUNGA SAFITRI", "ANDIKA DWI SAPUTRA", "ARI NANDA FEFRIAN", "BAYU AHMAD NUR IMAN", "CHANDRA WIRA ATMAJA", "DAFFA SAUQI", "DEBY ORLANDO PRATAMA", "DINO AFRIAN", "DZAIDAN AKMAL PRATAMA", "EKA SETYAWAN", "ELSYA ALFIANI", "FADLAN NABIL RIFQI SYAFIQ", "FHAREL HARDINATA M. NUR", "HANDY RYDHO WIJAYA", "IKA AGUSTINA", "INTAN NURAINI", "JANA SURYANA", "KHARISMA DINDA RAMADHANI", "M. LUTHFI MAULANA", "MUHAMMAD FADLI", "MUHAMMAD HAIQAL", "NESYA NANDINI", "NUUR MIFTAHUL JAUHAR", "PUTRI ADELINA FERANI", "PUTRI TANSYIER DEWI", "RAKA DRIMAHEZA", "RAYHAN RAYNANDA", "REHAN ADI PRASETIO", "RIKO ALFANANDO", "SHAFIRA NUR AZIZAH", "VIKA HERAWATI"],
    "X-DPIB-2": ["ADONIS NANDHITO", "AGUSTIAN FERNANDO", "AIKO ALVIZAUDRI KENATRA", "AKHMAD RIZKY MURTADO", "ALFINO PRAMANTA", "ALIFAH KUSUMA WARDANI", "ANDHIKA AZIZ PRATAMA", "ARETHA ZHIE ZHIE. S", "AULIA FEBRIYANA", "CAHAYA PUTRI MARIONA", "CHILA VIECHO NURHIDAYAH", "DAVA DANIL PARESA", "DIKA SAPUTRA", "DIVA APRILIA", "EKA PUTRA WIJAYA", "ELLAS TIRTA SAVANA", "FAIZ AL QORNI HAKIM", "GILANG SETIA AN", "HAFIZAH SETIA RAMADANI", "HENKY TRIYAN SYAH", "ILHAM DINATA", "JAENAL SOBIRIN", "KAYLA KANIA ALVIONA", "LUTHFI HANIF", "MELA NOVALIA", "MUHAMMAD FAHRI", "MUHAMMAD RAFLY AL - FAHREZY", "NINO OKTAVIANO SAPUTRA", "OSCHAR PARULIAN TAMPUBOLON", "PUTRI FEBRIANI", "RAHMAD RAMADAN", "RAMDA WIRAKKA PRATAMA", "REFAL FIRMANSYAH", "RIKA SAPUTRI", "SELFI MEDIARI A.ZYAHRA", "THOLIB ABDUL ALIM", "ZAHRA AMELIA"],
    "XI-DPIB-1": ["ABI DWI ARYANSYAH", "ADRIAN JULY SAPUTRA", "AGNES FIDELA ASMARA", "AHMAD FAQIH HUNTELAAR", "AININ DINIYA HAQQI", "ALVIN ANDRY PRATAMA", "ANGGIA FAULINA", "AZZAHRA KAYLA NURANISA", "BAGUS TRI PUJIANTO", "CELVIN NIKO PRATAMA", "DANI FIRMANSYAH", "DIKA PRATAMA", "FAJAR DZULKARNAEN", "GEVHANDRA MILANDO", "HENDRA KURNIAWAN", "INTAN BARO MAHARANI", "KEYSIA PUTRI HANDAYANI", "MARCEL ADITYA", "MUHAMAD FAREL RADITYA", "MUHAMMAD AGIL SAPUTRA", "MUHAMMAD ASFA ALDIKA", "MUHAMMAD HAFFIYAN ZASIN", "NINGRUM NUR ANNISA", "RAFFI GALIH PRASETYO", "RAKA RESKIADITIA HALTARA", "RIO ZET MIKO", "SYAMSUL ANWAR ARAFI"],
    "XI-DPIB-2": ["ADZKIA PURNOMO", "AFDAL NUR ROHIM", "AISYA AZZAHRA SINTIA", "ANDI SETIAWAN", "ARBA FIRMANSYAH", "ARDA JEPRIYAN SYACH", "AZIZ MAULANA ISHAK", "DIKKY DWI WIBOWO", "FADLI AZKA RAMANDIKA", "FAHRIZA RISWANDI", "FAREL PUTRA RAMADHAN", "GILANG SETIA AN", "INKA NABILA", "INNA RAFFA FIRIZKU SUBING", "IRWAN SAPUTRA", "MUHAMMAD IQBAL MAULANA", "MUHAMMAD NANDA ARYA REZA", "MUHAMMAD SYAHRUL MUNIR", "MUHAMMAD TAUFIQUZZIYAD", "NAIFA MEZZALUNA RAMADHANI", "NOVAL KHOIRUL EFENDI", "PANDU ADJIE DINATA", "QOIS NUR RAHMAN", "RAMA YOGA PRATAMA", "REFI ARTIKASARI", "RISKA RAHMAWARDANI", "RIZKY ADITYA", "RIZKY PRATAMA", "SITI RAHMAWATI", "SULTAN PASHA ALTAFA", "TIRTA NUR KHOIRUDIN", "VENY FERAWATI", "YUSUF RAMA WINATA", "ZHULFA ANISA RAYIKINANTI"],
    "XII-DPIB-1": ["AGUS MAULANA IKHSAN", "APRILIA DWI LESTARI", "AZ ZAHRA ANNISA", "CAHAYA WULANDARI", "CLAUDIA DHIZA SHEZA MALIKA", "DAMAR DWI BIMANDIKA", "DUWI NOFI WULANDARI", "LARASATI CAHYANING PUTRI HERNADI", "MUHAMAD LUTFI PRATAMA", "MUHAMMAD IHCAN ILHAM", "MUHAMMAD RIZKY", "NADIA NURUL AFIFA", "NAWANG AUFA QUROTA AKYUN", "QURROTA A'YUN", "RAIHAN HAKIM", "WANTI RAHMADANI", "WIDYA FADILLA ALBADRI", "AGNA KHOIRUL NISA", "ALL SHELLA VIERRANITHA AGLISKA", "CITRA ASTI MUTIA", "DAFFA KHUSNUREZA", "DAVA PURNIAWANDA", "DINI RAHMADANI", "EGI LISTIANTI", "FINKA INDAH ANGGRAINI", "HERLIZA AWANDA OCTARA", "KEYSHA ALLIFIA KHAIRUNISA", "M. PASYA FAUZI SOPIAN", "MUHAMMAD DHAFA", "RADITYA FEBRIANZA RIZANTHA", "RAFI DEBI ASMARA", "RENO ANDRE SAPUTRA", "REZA NURUL SAFITRI", "SAFIRA", "VIRGIAWAN LISTIANTO"],
    "XII-DPIB-2": ["ADLY YOVI SAPUTRA", "ANDREA DWI FERLIANSYAH", "BAYHAQQI RAFLI", "BAYU CATUR WIJANARKO", "GALANG SATRIA PUTRA", "IQBAL FERDIANSYAH", "LEO CHANDRA JAYA KESUMA", "LUCKY HERMAWAN", "MAULANA ABIYYU FAQIH", "MUHAMMAD FANI PRAJA MANDALA", "MUHAMMAD RAIHAN WIRAYUDA", "MUHAMMAD RISKY SYAPUTRA", "NABILA", "NASYA RAHMAWATI", "NESYA KURNIA SARI", "RAMADHAN ERLANG KHADAFI", "REVAN SEBASTIAN BELANDRI", "SISKA ANGGRAINI", "ADIKA ANANTA RAMLI", "AGAM PRASETIA JAYA", "ALIF DWI KUNCORO", "ALIFIA AULIA AMANDA", "ARIA AGUNG PRASETIO", "DIMAS MUHAMMAD AFRIZAL", "DUWI SANTIKA", "ESTER ROMAULI SIMATUPANG", "FIBRI LYIANA", "GALANG SAPUTRA", "GLEND ANDIKA PRATAMA", "GUSTI SONA ZULYAN PRATAMA", "HAYDEN RIO SAPUTRA", "MUHAMAD ARIF ALDO MAULANA", "NOVITA SARI", "PIRMANSYAH", "ROMLI AFFANDI", "YUNITA AGUSTINA"],
    "X-TKP": [
        "M RIFKI HERSILA PERATAMA", "ABDUL KHOLIK PRATAMA", "ADITYA JAYA SUTRA", "AFRIZAL RIZKY PRATAMA", "ALHAFID NURFADLI", 
        "AMANDA KIKI SAPUTRA", "ANDIKA PRATAMA", "ANDIKA PRATAMA", "ARAFFAH FADILLAH AKBAR", "ARDANI MISGIANTORO", 
        "ASRAF AHMAD PRIYADI", "AULIA ZAHRA NURSYAFITRI", "BAYU RENATA", "BELLARMINO BRANDO OASA", "BRILIYAN AKBAR", 
        "FAJAR ALIF PRASETIO", "FARDAN SETIAWAN", "GHAZY FARHAN PRATAMA", "HANIF ARDHITYA PRATAMA", "INDRA MAULANA", 
        "IQTARA HADI VALERIAN", "KEVIN RIDHO PRATAMA", "MARISCA NUR ANDINI", "MUBDIYANTO", "MUHAMAD ANDIEKA SYAHPUTRA", 
        "MUHAMMAD GADING MAS", "MUHAMMAD ROFI UDDIN", "REVAN RIDHO SETYAWAN", "REZA ALDIANO OKTORA", "RHEGA AQUM APFRANDA", 
        "RIDHO ALAMSYA", "RIDHO RAMADAN", "RIDHO RAMADHAN", "SAMUDRA NATA IRAWAN", "VEO RENTINO", 
        "WIRA FEBRIANSYAH"
    ],
    "XI-TKP": [
        "ABDUL SAPENDI", "ADITYA PRATAMA", "AHMAD ZAENURI", "ALDI PRATAMA", "ANDES HANAPI", 
        "ANDRA AHMAD MUSTAKIM", "ANGGA SAPUTRA", "ARUNG AKBAR ADIWANGSA", "AWAN FAUSTA", "BAYU RIDO AGUNG ALI", 
        "DIMAS MAULANA HERLAMBANG", "DINO ARDIANSYAH", "FAHRIZAL EKA WIJAYA", "FELIKS KRISDIANTORO", "GUSTI PRASETYO", 
        "IBNU CHOIRUL FIQRIANSYAH", "JESIKA ADITYA RAMADHANI", "JIBRIL ABBAS", "MUHAMAD ALI MAKSUN", "MUHAMMAD DZULFIQAR TAJJUDIN", 
        "MUHAMMAD RIZKY ADYTIA", "MUSTAFA WIRATAMA SAMPURNA JA", "RAHIL SAPUTRA", "REDI PERNANDA", "RINA SAFIRA FEBRIANA", 
        "RIZKI ALVIANSYAH", "SATRIA RAMADHAN", "SELO AL FATAH", "SUGI NAINGGOLAN", "WULANDARI", 
        "M. AL FAHRI"
    ],
    "XII-TKP-1": [
        "AHMAD HENGKI PRATAMA", "ANDIRA AKBAR", "ANGEL SAPUTRI", "ARDIANSAH", "ARKEN ARDIONO PUTRA", 
        "ASLAM AMINUDIN", "BUNGA HARUM BAHAGIA", "CHARRIZA ARTANTRI", "CHAYRA SELVA GEO VANISA", "DEO ADI PRATOPO", 
        "DEVA ARDI PRATAMA", "FATDIL PRATAMA", "FHAREL MARCO ERLANGGA", "GIGIH SEPTAYOGI", "HENDRO ARDIYANTO", 
        "IQBAL AL FARISKY", "M.FAJAR RAMADHAN", "MELZA", "MOH. ALI JA'FAR HSB", "MUHAMAD MULISOM", 
        "MUHAMMAD FAAKHRI", "MUHAMMAD SAKHA PERMANA RIY", "NADIA SAFIRA", "REHAN DANU SAPUTRA", "REHAN SURYA DINATA", 
        "RIAN SAPUTRA", "RIFQI ZAIN IDRAWAN", "ROFIQ FAIZAR", "RYCKO SAPUTRA PRATAMA", "SATRIO BAGAS OBRYAN PRASETY", 
        "SUCI RAMADANI", "TRI BAGUS PRASETIYO", "WILDAN WARDIANTO", "YELSA SINTIA BELA", "ZAINAL ABIDIN"
    ],
    "XII-TKP-2": [
        "ABI RAHMAN RIPAI", "ADI PURNOMO", "ADYTIA BAYU ANGGARA", "AHMAD HENDRI WIJAYA", "AL MU'MIN SAPUTRA", 
        "ALFA RIZKI WIRALDO PUTRA", "AMANDA FIKAYANI SARI", "ANGGA YUDA PRATAMA", "BAGUS ARDI PRAMUDYA", "DAMAR TRI RAHAYU", 
        "DAVA ADITYA NUGRAHA", "DWI SAPUTRA", "ERWIN MUDAFA", "FAHRI SETIAWAN", "FAIRUZ YUSTINO", 
        "FATIMAH DWI AZZAHRA", "FIQI ALBUQORI", "IRFAN MAULANA", "JAINAL MAHESA SAPUTRA", "JULIA ANGGRAINI", 
        "MOZZA PARAMITHA", "MUHAMAD DZIKRON AZIDANE", "MUHAMMAD FADLI JE.", "NIA SAPUTRI", "RENDI MUHAMMAT ERLANGGA", 
        "REZA ALBUKHARI", "RIAN ELFENDI", "RIPANDA PRATAMA", "SONYA ELFADILLAH", "VERONIKA ELI SETIOWATI", 
        "YOGA ANTAMA SEGALA"
    ]
};
